### ISSUE TITLE
CUHK03 dataset no longer available - mirror?

### ISSUE THREAD

**Issue by rleaver152** [Nirvan101/Person-Re-identification#17]
The CUHK03 dataset is no longer available from the provided links.  Is there a mirror or alternative download link?

**Comment by amalinazakaria** [comment]
Have you got the dataset?

**Comment by rleaver152** [comment]
yes thanks

**Comment by amalinazakaria** [comment]
Can you share where u get the dataset?

**Comment by rleaver152** [comment]
I just googled for its name,  sorry can’t remember the exact location

**Comment by rleaver152** [comment]
I think this was it  https://chowdera.com/2022/01/202201041911261238.html#1_CUHK03targz__46

**Comment by amalinazakaria** [comment]
Oh okay thank you so much!
